hits = [
    {
                    "_index": "glds",
                    "_type": "docs",
                    "_id": "GLDS-267",
                    "_score": 13.555656,
                    "_source": {
                        "Authoritative Source URL": "GLDS-267/",
                        "Flight Program": "International Space Station (ISS)",
                        "Mission": {
                            "End Date": "18-May-2014",
                            "Start Date": "18-Apr-2014",
                            "Name": "SpaceX-3"
                        },
                        "Material Type": "root",
                        "Project Identifier": "VEGGIE",
                        "Accession": "GLDS-267",
                        "Study Identifier": "Veggie Tech Demo 01A",
                        "Study Protocol Name": "sample collection     nucleic acid extraction     library construction-16S     nucleic acid sequencing-16S     library construction-ITS     nucleic acid sequencing-ITS",
                        "Study Assay Technology Type": "nucleotide sequencing     nucleotide sequencing",
                        "Acknowledgments": "Astronauts Steve Swanson Scott Kelly Kjell Lindgren and Shane Kimbrough. Veg and Veggie members especially JC Carver Chuck Spern Nicole Dufour. Science team members Bob Morrow Gerard Newsham.",
                        "Study Assay Technology Platform": "Illumina MiSeq     Illumina MiSeq",
                        "Study Person": {
                            "Last Name": "Khodadad",
                            "Middle Initials": "L. M.",
                            "First Name": "Christina"
                        },
                        "Study Protocol Type": "sample collection     nucleic acid extraction     library construction     nucleic acid sequencing     library construction     nucleic acid sequencing",
                        "Space Program": "NASA",
                        "Study Title": "Microbiological and nutritional analysis of lettuce crops grown on the International Space Station-VEG01A",
                        "Study Factor Type": "Space Flight, organism part",
                        "Study Public Release Date": "1582261200",
                        "Parameter Value": "",
                        "thumbnail": "/genelab/img/GLDS267__study_image.png",
                        "Study Factor Name": "Spaceflight     Organism Part",
                        "Study Assay Measurement Type": "metagenome profiling     metagenome profiling",
                        "Project Type": "Spaceflight Study",
                        "Factor Value": "",
                        "Data Source Accession": "",
                        "Data Source Type": "cgene",
                        "Project Title": "Veggie   Vegetable Production System Proof of Concept Flight",
                        "Study Funding Agency": "Funding was provided by NASA  s Space Life and Physical Sciences (SLPS) Space Biology Program",
                        "Study Protocol Description": "At the completion of the VEG-01A experiments plants were harvested. Plant leaves were wrapped in aluminum foil and placed in -80C (MELFI) until return. Two plant pillows with root material from each experiment were also frozen at -80C until return. Parallel ground experiments were handled and sampled identical to flight with a 24 hour delay.     Temperature was maintained during the return of tissues to Kennedy Space Center where they were also maintained at -80C until processing. Plant leaf material was processed immediately upon thawing and pillows containing roots were thawed at 4 - 8C overnight before sampling was completed. All leaf material was divided for chemical microbiological and molecular analysis.",
                        "Experiment Platform": "Vegetable Production System (VEGGIE)",
                        "Characteristics": "",
                        "Study Grant Number": "",
                        "Study Publication Author List": "Khodadad CLM Hummerick ME Spencer LE Dixit AR Richards JT Romeyn MW Smith TM Wheeler RM Massa GD",
                        "Project Link": "https://lsda.jsc.nasa.gov/Experiment/exper/13890",
                        "Study Publication Title": "Microbiological and nutritional analysis of lettuce crops grown on the International Space Station",
                        "Managing NASA Center": "Kennedy Space Center (KSC)",
                        "Study Description": "Lettuce crops grown in the Veggie payload aboard ISS harvested and returned for chemical microbiological and molecular analysis",
                        "organism": "Microbiota"
                    },
                    "highlight": {
                        "all": [
                            "International <em>Space</em> Station (ISS)",
                            "<em>Space</em> Flight, organism part",
                            "<em>cgene</em>",
                            "Funding was provided by NASA  s <em>Space</em> Life and Physical Sciences (SLPS) <em>Space</em> Biology Program",
                            "Kennedy <em>Space</em> Center (KSC)"
                        ]
                    }
                },
                {
                    "_index": "glds",
                    "_type": "docs",
                    "_id": "GLDS-303",
                    "_score": 13.398356,
                    "_source": {
                        "Authoritative Source URL": "GLDS-303/",
                        "Flight Program": "Internation Space Station (ISS)",
                        "Mission": {
                            "End Date": "",
                            "Start Date": "",
                            "Name": ""
                        },
                        "Material Type": "Cells",
                        "Project Identifier": "ISS-MO (MT-1B)",
                        "Accession": "GLDS-303",
                        "Study Identifier": "PRJNA637984",
                        "Study Protocol Name": "sample collection     nucleic acid extraction     library construction     nucleic acid sequencing     sequence assembly",
                        "Study Assay Technology Type": "nucleotide sequencing",
                        "Acknowledgments": "",
                        "Study Assay Technology Platform": "Illumina NovaSeq 6000",
                        "Study Person": {
                            "Last Name": "Venkateswaran     Daudu",
                            "Middle Initials": "",
                            "First Name": "Kasthuri     Robert"
                        },
                        "Study Protocol Type": "sample collection     nucleic acid extraction     library construction     nucleic acid sequencing     sequence assembly",
                        "Space Program": "NASA",
                        "Study Title": "ISS Bacillus Genomes",
                        "Study Factor Type": "strain, Space Flight",
                        "Study Public Release Date": "1592193600",
                        "Parameter Value": "",
                        "thumbnail": "/genelab/img/GLDS303__study_image.png",
                        "Study Factor Name": "Spaceflight     Strain",
                        "Study Assay Measurement Type": "genome sequencing",
                        "Project Type": "Spaceflight Study",
                        "Factor Value": "",
                        "Data Source Accession": "PRJNA637984",
                        "Data Source Type": "cgene",
                        "Project Title": "ISS Microbial Observatory (Microbial Tracking-1B)",
                        "Study Funding Agency": "This research was funded by a 2012 Space Biology NNH12ZTT001N grant nos. 19-12829-26 under Task Order NNN13D111T award to KV.",
                        "Study Protocol Description": "During the microbial tracking investigation to characterize airborne and surface-associated microbial population aboard the International Space Station (ISS) samples were collected from 6 locations across the ISS and ground samples were collected from Crew resupply vehicle (CRV). A sterile polyester wipe premoistened with Phosphate buffered saline (PBS) was used to collect the samples from various areas across those 6 locations and the details and description of the sample collection and cultivation have already been reported in Checinska et al 2019 and Singh et al 2018.",
                        "Experiment Platform": "",
                        "Characteristics": "",
                        "Study Grant Number": "19-12829-26",
                        "Study Publication Author List": "Daudu R Singh NK Wood JM Debieu M O  Hara NB Mason C and Venkateswaran K",
                        "Project Link": "https://lsda.jsc.nasa.gov/Experiment/exper/13630",
                        "Study Publication Title": "Draft Genome Sequences of Bacillaceae strains isolated from International Space Station",
                        "Managing NASA Center": "Jet Propulsion Laboratory (JPL)",
                        "Study Description": "SRA of spore forming Bacillus strains isolated from various areas of the ISS during Microbial tracking investigation",
                        "organism": "Bacillus amyloliquefaciens, Thermus amyloliquefaciens, Paenibacillus polymyxa, Bacillus firmus, Bacillus cereus thuringiensis"
                    },
                    "highlight": {
                        "all": [
                            "Internation <em>Space</em> Station (ISS)",
                            "strain, <em>Space</em> Flight",
                            "<em>cgene</em>",
                            "This research was funded by a 2012 <em>Space</em> Biology NNH12ZTT001N grant nos. 19-12829-26 under Task Order",
                            "Draft Genome Sequences of Bacillaceae strains isolated from International <em>Space</em> Station"
                        ]
                    }
                },
                {
                    "_index": "glds",
                    "_type": "docs",
                    "_id": "GLDS-41",
                    "_score": 13.290899,
                    "_source": {
                        "Authoritative Source URL": "GLDS-41/",
                        "Flight Program": "International Space Station (ISS)",
                        "Mission": {
                            "End Date": "Nov-27-2009",
                            "Start Date": "Nov-16-2009",
                            "Name": "STS-129"
                        },
                        "Material Type": "",
                        "Project Identifier": "CERISE",
                        "Accession": "GLDS-41",
                        "Study Identifier": "E-GEOD-27338",
                        "Study Protocol Name": "P-GSE27338-1     P-GSE27338-6     P-GSE27338-5     P-GSE27338-3     P-GSE27338-2     P-GSE27338-4     P-GSE27338-7",
                        "Study Assay Technology Type": "DNA microarray",
                        "Acknowledgments": "",
                        "Study Assay Technology Platform": "Agilent",
                        "Study Person": {
                            "Last Name": "Higashibata     Hashizume",
                            "Middle Initials": "",
                            "First Name": "Akira     Toko"
                        },
                        "Study Protocol Type": "bioassay_data_transformation     image_aquisition     hybridization     nucleic_acid_extraction     grow     labeling     feature_extraction",
                        "Space Program": "JAXA",
                        "Study Title": "Microgravity effect on C. elegans N2/VC (CERISE 8days)",
                        "Study Factor Type": "Gravitation",
                        "Study Public Release Date": "1340942400",
                        "Parameter Value": "",
                        "thumbnail": "/genelab/img/GLDS41__study_image.png",
                        "Study Factor Name": "gravity",
                        "Study Assay Measurement Type": "transcription profiling",
                        "Project Type": "Spaceflight Study",
                        "Factor Value": "",
                        "Data Source Accession": "E-GEOD-27338",
                        "Data Source Type": "cgene",
                        "Project Title": "C. elegans RNAi space experiment: CERISE",
                        "Study Funding Agency": "",
                        "Study Protocol Description": "ID_REF =",
                        "Experiment Platform": "KIBO",
                        "Characteristics": "",
                        "Study Grant Number": "UK MRC (G0801271) and the US NIH NIAMS (AR054342)",
                        "Study Publication Author List": "Atsushi Higashitani Toko Hashizume Tomoko Sugimoto Chihiro Mori Kanako Nemoto Timothy Etheridge Nahoko Higashitani Takako Takanami Hiromi Suzuki Keiji Fukui Takashi Yamazaki Noriaki Ishioka Nathaniel Szewczyk and Akira Higashibata     Timothy Etheridge Kanako Nemoto Toko Hashizume Chihiro Mori Tomoko Sugimoto Hiromi Suzuki Keiji Fukui Takashi Yamazaki Akira Higashibata Nathaniel J. Szewczyk Atsushi Higashitani",
                        "Project Link": "http://iss.jaxa.jp/en/kiboexp/news/cerise_start.html",
                        "Study Publication Title": "C. elegans RNAi space experiment (CERISE) in Japanese Experiment",
                        "Managing NASA Center": "NA",
                        "Study Description": "Microgravity effect on C. elegans gene expression was analysed by whole genome microarray. The worms were cultivated under microgravity for 8 days in the Japanese Module of the International Space Station. The samples of this study were divided three experimental groups: 1. microgravity for 8 days 2. artificial 1G control for 8 days on orbit 3. ground 1G control for 8 days This study was repeated with three biological and two technical replicates.",
                        "organism": "Caenorhabditis elegans"
                    },
                    "highlight": {
                        "all": [
                            "International <em>Space</em> Station (ISS)",
                            "<em>cgene</em>",
                            "C. elegans RNAi <em>space</em> experiment: CERISE",
                            "C. elegans RNAi <em>space</em> experiment (CERISE) in Japanese Experiment",
                            "The worms were cultivated under microgravity for 8 days in the Japanese Module of the International <em>Space</em>"
                        ]
                    }
                },
                {
                    "_index": "glds",
                    "_type": "docs",
                    "_id": "GLDS-114",
                    "_score": 13.225005,
                    "_source": {
                        "Authoritative Source URL": "GLDS-114/",
                        "Flight Program": "International Space Station (ISS)",
                        "Material Type": "Human fibroblasts AG01522",
                        "Project Identifier": "Micro-7",
                        "Accession": "GLDS-114",
                        "Project Link": "https://lsda.jsc.nasa.gov/scripts/experiment/exper.aspx?exp_index=13378",
                        "Study Identifier": "GSE93860",
                        "Study Protocol Name": "sample collection     RNA extraction     labeling     nucleic acid hybridization     data collection     normalization data transformation",
                        "Study Assay Technology Type": "DNA microarray",
                        "Acknowledgments": "",
                        "Study Assay Technology Platform": "Agilent",
                        "Study Person": {
                            "Last Name": "Lu     Zhang     Yared     Wu",
                            "Middle Initials": "",
                            "First Name": "Tao     Ye     K     Honglu"
                        },
                        "Study Protocol Type": "sample collection     RNA extraction     labeling     nucleic acid hybridization     data collection     normalization data transformation",
                        "Space Program": "NASA",
                        "Study Title": "Gene Expression Profile Changes due to Bleomycin-Induced DNA Damage in Human Fibroblasts in Space",
                        "Study Factor Type": "Weightlessness, treatment",
                        "Study Public Release Date": "1484899200",
                        "Parameter Value": "",
                        "thumbnail": "/genelab/img/GLDS114__study_image.png",
                        "Study Factor Name": "Microgravity     Bleomycin Treatment",
                        "Study Assay Measurement Type": "transcription profiling",
                        "Project Type": "Spaceflight study",
                        "Factor Value": "",
                        "Data Source Accession": "GSE93860",
                        "Data Source Type": "cgene",
                        "Project Title": "mRNA Expression Profiles in Cultured Human Fibroblasts in Space",
                        "Study Funding Agency": "This work was supported by the NASA Fundamental Space Biology Program.",
                        "Study Protocol Description": "Human fibroblasts AG01522 were cultured at 37 xbaC in alpha-MEM supplemented with 10% heat-inactivated fetal bovine serum and Penicillin and Streptomycin to conflence.",
                        "Experiment Platform": "BioCell Habitat",
                        "Characteristics": "",
                        "Study Grant Number": "",
                        "Study Publication Author List": "Lu T Zhang Y Kidane Y Feiveson A Stodieck L Karouia F Ramesh G Rohde L Wu H.",
                        "Mission": {
                            "End Date": "18-May-2014",
                            "Start Date": "18-Apr-2014",
                            "Name": "SpaceX-3"
                        },
                        "Study Publication Title": "Cellular responses and gene expression profile changes due to bleomycin-induced DNA damage in human fibroblasts in space",
                        "Managing NASA Center": "Ames Research Center (ARC)",
                        "Study Description": "To understand gene expression responses in confluent human fibroblast in microgravity conditions to bleomycin treatment. Confluent human fibroblasts AG01522 were flown to the International Space Station (ISS). After three day on ISS the cells were treated with bleomycin at 1.0 microg/ml for 3 hours. The cells were washed and fixed with RNALater. Total RNA were isolated after the samples were returned to earth and subject to microarray analysis.",
                        "organism": "Homo sapiens"
                    },
                    "highlight": {
                        "all": [
                            "International <em>Space</em> Station (ISS)",
                            "<em>cgene</em>",
                            "mRNA Expression Profiles in Cultured Human Fibroblasts in <em>Space</em>",
                            "This work was supported by the NASA Fundamental <em>Space</em> Biology Program.",
                            "Confluent human fibroblasts AG01522 were flown to the International <em>Space</em> Station (ISS)."
                        ]
                    }
                },
                {
                    "_index": "glds",
                    "_type": "docs",
                    "_id": "GLDS-177",
                    "_score": 13.133408,
                    "_source": {
                        "Authoritative Source URL": "GLDS-177/",
                        "Flight Program": "Internation Space Station (ISS)",
                        "Material Type": "",
                        "Project Identifier": "VEGGIE",
                        "Mission": {
                            "End Date": "18-May-2014",
                            "Start Date": "18-Apr-2014",
                            "Name": "SpaceX-3"
                        },
                        "Study Identifier": "PRJNA437451",
                        "Study Protocol Name": "sample collection, nucleic acid sequencing, sequence assembly",
                        "Study Assay Technology Type": "nucleotide sequencing",
                        "Acknowledgments": "",
                        "Study Assay Technology Platform": "Illumina",
                        "Study Person": {
                            "Last Name": "Venkateswaran, Urbaniak",
                            "First Name": "Kasthuri, Camilla",
                            "Middle Initials": ", "
                        },
                        "Study Protocol Type": "sample collection, nucleic acid sequencing, sequence assembly",
                        "Space Program": "NASA",
                        "Study Title": "Draft Genome Sequences of Two Fusarium oxysporum Isolates Cultured from Infected Zinnia hybrida Plants Grown on the International Space Station",
                        "Study Factor Type": "Space Flight",
                        "Study Public Release Date": "0000000000",
                        "Parameter Value": "",
                        "thumbnail": "/genelab/img/GLDS177__study_image.png",
                        "Study Factor Name": "Spaceflight",
                        "Study Assay Measurement Type": "genome sequencing",
                        "Project Type": "Spaceflight Study",
                        "Factor Value": "",
                        "Data Source Accession": "PRJNA437451",
                        "Data Source Type": "cgene",
                        "Project Title": "Veggie Vegetable Production System Proof of Concept Flight",
                        "Study Funding Agency": "This research was funded by a 2012 Space Biology NNH12ZTT001N grant number 19-12829-26 under Task Order NNN13D111T",
                        "Accession": "GLDS-177",
                        "Study Protocol Description": "During the course of the Veggie project (a vegetable production system flown onboard the International Space Station [ISS] to study the effects of the space environment on plant growth and function), Zinnia hybrida plants became afflicted with a foliar, stem, and root rot disease caused by the fungus Fusarium oxysporum. Isolates were cultured from the leaf (VEG-01C1) and the root (VEG-01C2) of these infected plants., The whole-genome sequences were paired-end sequenced (2 x 100 bp) on the Illumina HiSeq platform with a 350-bp insert size., Postprocessed reads were de novo assembled with ABySS version 2.0.2 using k-mer sizes of 80 (VEG-01C1) and 88 (VEG-01C2).",
                        "Experiment Platform": "Vegetable Production System (VEGGIE)",
                        "Characteristics": "",
                        "Study Grant Number": "19-12829-26",
                        "Study Publication Author List": "Urbaniak C, Massa G, Hummerick M, Khodadad C, Schuerger A, Venkateswaran K",
                        "Project Link": "https://lsda.jsc.nasa.gov/Experiment/exper/13890",
                        "Study Publication Title": "Draft Genome Sequences of Two Fusarium oxysporum Isolates Cultured from Infected Zinnia hybrida Plants Grown on the International Space Station.",
                        "Managing NASA Center": "Ames Research Center (ARC)",
                        "Study Description": "Draft genome sequences of two Fusarium oxysporum isolates cultured from infected Zinnia hybrida plants grown on the International Space Station",
                        "organism": ""
                    },
                    "highlight": {
                        "all": [
                            "Internation <em>Space</em> Station (ISS)",
                            "Fusarium oxysporum Isolates Cultured from Infected Zinnia hybrida Plants Grown on the International <em>Space</em>",
                            "<em>Space</em> Flight",
                            "<em>cgene</em>",
                            "This research was funded by a 2012 <em>Space</em> Biology NNH12ZTT001N grant number 19-12829-26 under Task Order"
                        ]
                    }
                },
                {
                    "_index": "glds",
                    "_type": "docs",
                    "_id": "GLDS-132",
                    "_score": 12.97792,
                    "_source": {
                        "Authoritative Source URL": "GLDS-132/",
                        "Flight Program": "International Space Station (ISS)",
                        "Material Type": "Soil",
                        "Project Identifier": "NA",
                        "Accession": "GLDS-132",
                        "Project Link": "",
                        "Study Identifier": "PRJNA355122",
                        "Study Protocol Name": "sample collection     nucleic acid extraction     library construction     nucleic acid sequencing     sequence assembly",
                        "Study Assay Technology Type": "nucleotide sequencing",
                        "Acknowledgments": "We thank the implementation team of the Center for Advanced Study in Space and Duane Pierson Johnson Space Center for providing the A. niger strain. The other fungal strains are maintained at Lawrence Berkeley National Laboratory.",
                        "Study Assay Technology Platform": "Illumina",
                        "Study Person": {
                            "Last Name": "Singh     Blachowicz     Romsdahl     Wang     Torok     Venkateswaran",
                            "Middle Initials": "K",
                            "First Name": "Nitin     Adriana     Jillian     Clay     Tamas     Kasthuri"
                        },
                        "Study Protocol Type": "sample collection     nucleic acid extraction     library construction     nucleic acid sequencing     sequence assembly",
                        "Space Program": "NASA",
                        "Study Title": "Whole genome sequencing and assembly of Eukaryotic microbes isolated from ISS environmental surface Kirovograd region soil Chernobyl Nuclear Power Plant and Chernobyl Exclusion Zone",
                        "Study Factor Type": "Radiation",
                        "Study Public Release Date": "1492066800",
                        "Parameter Value": "",
                        "thumbnail": "/genelab/img/GLDS132__study_image.png",
                        "Study Factor Name": "radiation",
                        "Study Assay Measurement Type": "genome sequencing",
                        "Project Type": "Spaceflight Study",
                        "Factor Value": "",
                        "Data Source Accession": "PRJNA355122",
                        "Data Source Type": "cgene",
                        "Project Title": "",
                        "Study Funding Agency": "Part of the research described in this publication was carried out at the Jet Propulsion Laboratory (JPL) California Institute of Technology under a contract with NASA. This research was supported by the JPL Advanced Concept Development fund awarded to K.V. that funded a student fellowship to A.B. Part of the research described in this publication was carried out at Lawrence Berkeley National Laboratory (T.T.) and the University of Southern California (C.W.) which funded a student fellowship to J.R.",
                        "Study Protocol Description": "We thank the implementation team of the Center for Advanced Study in Space and Duane",
                        "Experiment Platform": "",
                        "Characteristics": "",
                        "Study Grant Number": "",
                        "Study Publication Author List": "Singh NK Blachowicz A Romsdahl J Wang C Torok T Venkateswaran K.",
                        "Mission": {
                            "End Date": "",
                            "Start Date": "",
                            "Name": ""
                        },
                        "Study Publication Title": "Draft Genome Sequences of Several Fungal Strains Selected for Exposure to Microgravity at the International Space Station.",
                        "Managing NASA Center": "JPL",
                        "Study Description": "The whole-genome sequences of eight fungal strains that were selected for exposure to microgravity at the International Space Station are presented here. These baseline sequences will help to understand the observed production of novel bioactive compounds.",
                        "organism": "Aspergillus terreus, Aureobasidium pullulans, Cladosporium sphaerospermum, Fusarium solani, Cladosporium cladosporioides, Trichoderma virens, Beauveria bassiana, Aspergillus niger"
                    },
                    "highlight": {
                        "all": [
                            "International <em>Space</em> Station (ISS)",
                            "We thank the implementation team of the Center for Advanced Study in <em>Space</em> and Duane Pierson Johnson",
                            "<em>Space</em> Center for providing the A. niger strain.",
                            "<em>cgene</em>",
                            "We thank the implementation team of the Center for Advanced Study in <em>Space</em> and Duane"
                        ]
                    }
                },
                {
                    "_index": "glds",
                    "_type": "docs",
                    "_id": "GLDS-67",
                    "_score": 12.966176,
                    "_source": {
                        "Authoritative Source URL": "GLDS-67/",
                        "Flight Program": "International Space Station (ISS)",
                        "Mission": {
                            "End Date": "10-Jun-2015",
                            "Start Date": "10-Nov-2014",
                            "Name": "ISS Increments 42,43"
                        },
                        "Material Type": "",
                        "Project Identifier": "ISS-MO",
                        "Accession": "GLDS-67",
                        "Study Identifier": "MO-BSL-2",
                        "Study Protocol Name": "sample collection     nucleic acid extraction     library construction     nucleic acid sequencing     sequence assembly",
                        "Study Assay Technology Type": "nucleotide sequencing",
                        "Acknowledgments": "We thank Nitin Singh and Aleksandra Checinska.",
                        "Study Assay Technology Platform": "Illumina",
                        "Study Person": {
                            "Last Name": "Venkateswaran",
                            "Middle Initials": "",
                            "First Name": "Kasthuri"
                        },
                        "Study Protocol Type": "sample collection was done using sterile moisten wipes     nucleic acid extraction was done usinq Qiagen DNA extraction kit as per manufacturer instruction     TruSeq DNA PCR-free was used as per manufacturer instruction      Illumina NextSeq     sequence assembly using  a5 genome assembler",
                        "Space Program": "NASA",
                        "Study Title": "Microbial Observatory (ISS-MO): Study of BSL-2 bacterial isolates from the International Space Station",
                        "Study Factor Type": "Weightlessness",
                        "Study Public Release Date": "1467950400",
                        "Parameter Value": "",
                        "thumbnail": "/genelab/img/GLDS67__study_image.png",
                        "Study Factor Name": "Microgravity",
                        "Study Assay Measurement Type": "genome sequencing",
                        "Project Type": "Spaceflight Study",
                        "Factor Value": "",
                        "Data Source Accession": "",
                        "Data Source Type": "cgene",
                        "Project Title": "Microbial Tracking Payload Series (Microbial Observatory-1)",
                        "Study Funding Agency": "Funding provided by NASA ISS-based experiment and Space Biology experiment under NNH12ZTT001N grant no. 19-12829-26 and 19-12829-27",
                        "Study Protocol Description": "Sample kit preparation and sample collection",
                        "Experiment Platform": "International Space Station (ISS)",
                        "Characteristics": "",
                        "Study Grant Number": "NNH12ZTT001N grant no. 19-12829-26 and 19-12829-27",
                        "Study Publication Author List": "Aleksandra Checinska Sielaff Nitin K. Singh Jonathan E. Allen James Thissen Crystal Jaing Kasthuri Venkateswaran     Singh NK Bezdan D Checinska Sielaff A Wheeler K Mason CE Venkateswaran K.",
                        "Project Link": "https://lsda.jsc.nasa.gov/scripts/experiment/exper.aspx?exp_index=13629",
                        "Study Publication Title": "Draft Genome Sequences of BSL-2 Opportunistic Pathogens Isolated from the Environmental Surfaces of the International Space Station.     Multi-drug resistant Enterobacter bugandensis species isolated from the International Space Station and comparative genomic analyses with human pathogenic strains",
                        "Managing NASA Center": "Jet Propulsion Laboratory (JPL)",
                        "Study Description": "In an on-going Microbial Observatory experimental investigation on the International Space Station (ISS) multiple bacterial isolates of Biosafety Level 2 (BSL-2) were isolated and identified. The antibiotic susceptibility pattern was tested in these BSL-2 isolates for the following antibiotics: cefazolin ciprofloxacin cefoxitin erythromycin gentamycin oxacillin penicillin rifampin tobramycin and many of the BSL-2 isolates showed multiple drug resistance. Among these isolates 21 strains were chosen for whole genome sequencing (WGS) for a possible lead to develop appropriate countermeasures. In addition the genomic data would enable to determine the influence of microgravity on the pathogenicity and virulence in the BSL-2 microorganisms.",
                        "organism": "Klebsiella, Staphylococcus, Enterobacter, Staphylococcus aureus, Pantoea conspicua, Acinetobacter pittii"
                    },
                    "highlight": {
                        "all": [
                            "International <em>Space</em> Station (ISS)",
                            "Microbial Observatory (ISS-MO): Study of BSL-2 bacterial isolates from the International <em>Space</em> Station",
                            "<em>cgene</em>",
                            "Funding provided by NASA ISS-based experiment and <em>Space</em> Biology experiment under NNH12ZTT001N grant no",
                            "International <em>Space</em> Station (ISS)"
                        ]
                    }
                },
                {
                    "_index": "glds",
                    "_type": "docs",
                    "_id": "GLDS-116",
                    "_score": 12.953244,
                    "_source": {
                        "Authoritative Source URL": "GLDS-116/",
                        "Flight Program": "Space Transportation System (STS)",
                        "Mission": {
                            "End Date": "21-Jul-2011",
                            "Start Date": "08-Jul-2011",
                            "Name": "STS-135"
                        },
                        "Material Type": "Skin",
                        "Project Identifier": "NA",
                        "Accession": "GLDS-116",
                        "Study Identifier": "STS-135_Skin",
                        "Study Protocol Name": "sample collection     RNA extraction     labeling     nucleic acid hybridization     data collection     normalization data transformation     extraction     mass spectrometry     MS data transformation     Radiation Dosimetry",
                        "Study Assay Technology Type": "mass spectrometry     DNA microarray",
                        "Acknowledgments": "We would like to thank Amgen and their support team for the opportunity to participate in this study and BioServe Space Technologies at the University of Colorado at Boulder for organizing and overseeing this project. We would also like to thank all team members of the Ferguson & Bateman labs who participated in the tissue processing at KSC. We would like to thank Paula Dumars and Vera Vizir of the BSP and Ames Research Center as well as the KSC SLSL support staff. We would like to thank Janice Jones Elizabeth Morin-Kensicki at Metabolon Inc for their help with interpretation of the metabolic profile of the skin samples.",
                        "Study Assay Technology Platform": "Thermo-Finnigan Mass Spectrometer     RT2 ProfilerTM PCR Array",
                        "Study Person": {
                            "Last Name": "Mao",
                            "Middle Initials": "W",
                            "First Name": "Xiao"
                        },
                        "Study Protocol Type": "sample collection     RNA extraction     labeling     nucleic acid hybridization     data collection     normalization data transformation     extraction     mass spectrometry     MS data transformation     Radiation Dosimetry",
                        "Space Program": "NASA",
                        "Study Title": "Biological and Metabolic Response in STS-135 Space-flown Mouse Skin",
                        "Study Factor Type": "Absorbed Radiation Dose, Space Flight",
                        "Study Public Release Date": "1493352000",
                        "Parameter Value": "",
                        "thumbnail": "/genelab/img/GLDS116__study_image.png",
                        "Study Factor Name": "Spaceflight     Absorbed Radiation Dose",
                        "Study Assay Measurement Type": "metabolite profiling     transcription profiling",
                        "Project Type": "Spaceflight Study",
                        "Factor Value": "",
                        "Data Source Accession": "",
                        "Data Source Type": "cgene",
                        "Project Title": "Biological and metabolic response in STS-135 space-flown mouse skin",
                        "Study Funding Agency": "This study was supported by NASA grant NNX10AJ31G and the LLUMC Department of Radiation Medicine",
                        "Study Protocol Description": "Female C57BL/6CR mice were flown in STS-135 using NASA  s animal enclosure modules (AEMs). A set of ground controls (Ground AEMs) was housed at the Space Life Science Laboratory (SLSL) at KSC. Ground AEM control mice were placed into the same hardware using in flight to mimic the environmental parameters such as temperature humidity and carbon dioxide levels of the space shuttle middeck. AEM controls were fed a special NASA food bar diet same as space flown mice. All animals were maintained on a 12-h on/off light cycle.",
                        "Experiment Platform": "Animal Enclosure Module (AEM)",
                        "Characteristics": "",
                        "Study Grant Number": "NNX10AJ31G",
                        "Study Publication Author List": "X. W. Mao M. J. Pecaut L. S. Stodieck V. L. Ferguson T. A. Bateman M. L. Bouxsein and D. S. Gridley",
                        "Project Link": "https://lsda.jsc.nasa.gov/scripts/experiment/exper.aspx?exp_index=13508",
                        "Study Publication Title": "Biological and Metabolic Response in STS-135 Space-flown Mouse Skin",
                        "Managing NASA Center": "Ames Research Center (ARC)",
                        "Study Description": "Changes in gene expression profiles implicated in oxidative stress and in ECM remodeling in mouse skin were examined after space flight. The metabolic effects of space flight in skin tissues were also characterized.",
                        "organism": "Mus musculus"
                    },
                    "highlight": {
                        "all": [
                            "<em>Space</em> Transportation System (STS)",
                            "Biological and Metabolic Response in STS-135 <em>Space</em>-flown Mouse Skin",
                            "Absorbed Radiation Dose, <em>Space</em> Flight",
                            "<em>cgene</em>",
                            "Biological and metabolic response in STS-135 <em>space</em>-flown mouse skin"
                        ]
                    }
                },
                {
                    "_index": "glds",
                    "_type": "docs",
                    "_id": "GLDS-87",
                    "_score": 12.883446,
                    "_source": {
                        "Authoritative Source URL": "GLDS-87/",
                        "Flight Program": "Space Transportation System (STS)",
                        "Mission": {
                            "End Date": "21-Jul-2011",
                            "Start Date": "08-Jul-2011",
                            "Name": "STS-135"
                        },
                        "Material Type": "Retina",
                        "Project Identifier": "NA",
                        "Accession": "GLDS-87",
                        "Study Identifier": "Zanello",
                        "Study Protocol Name": "growth protocol     sample collection     RNA extraction     labeling     nucleic acid hybridization     normalization data transformation     Radiation Dosimetry     GeneLab microarray data processing protocol",
                        "Study Assay Technology Type": "DNA microarray",
                        "Acknowledgments": "The authors would like to thank NASA Human Research Program and the UTMB Genomics Core for their help in conducting analysis of microarray results",
                        "Study Assay Technology Platform": "Affymetrix",
                        "Study Person": {
                            "Last Name": "Zanello",
                            "Middle Initials": "B",
                            "First Name": "Susana"
                        },
                        "Study Protocol Type": "growth protocol     sample collection     RNA extraction     labeling     nucleic acid hybridization     normalization data transformation     Radiation Dosimetry     data transformation",
                        "Space Program": "NASA",
                        "Study Title": "Spaceflight effects on the mouse retina: Histological gene expression and epigenetic changes after flight on STS-135",
                        "Study Factor Type": "Cosmic Radiation, Space Flight",
                        "Study Public Release Date": "1481864400",
                        "Parameter Value": "",
                        "thumbnail": "/genelab/img/GLDS87__study_image.png",
                        "Study Factor Name": "Spaceflight     Cosmic Radiation",
                        "Study Assay Measurement Type": "transcription profiling",
                        "Project Type": "Spaceflight study",
                        "Factor Value": "",
                        "Data Source Accession": "",
                        "Data Source Type": "cgene",
                        "Project Title": "Spaceflight Effects on the Mouse Retina: Histological Gene Expression and Epigenetic Changes After Flight",
                        "Study Funding Agency": "Funding was provided by NASA Human Research Program",
                        "Study Protocol Description": "Mice were flown onboard STS-135 that lifted off at 11:29 am EDT on July 8 2011 and landed at 5:57 am on July 21 2011. The mission duration was 12 days 18 hours 28 minutes.",
                        "Experiment Platform": "Animal Enclosure Module (AEM)",
                        "Characteristics": "",
                        "Study Grant Number": "ARC00XX119",
                        "Study Publication Author List": "Theriot C. and Zanello S.B.",
                        "Project Link": "https://lsda.jsc.nasa.gov/scripts/experiment/exper.aspx?exp_index=1857",
                        "Study Publication Title": "Molecular Effects of Spaceflight in the Mouse Eye after Space Shuttle Mission STS-135",
                        "Managing NASA Center": "Johnson Space Center (JSC)",
                        "Study Description": "We report the findings of an animal experiment onboard STS-135 investigating the molecular aspects of the impact of spaceflight on retinal biology by performing differential gene expression profiling between mice flown onboard STS-135 and their ground control counterparts.",
                        "organism": "Mus musculus"
                    },
                    "highlight": {
                        "all": [
                            "<em>Space</em> Transportation System (STS)",
                            "Cosmic Radiation, <em>Space</em> Flight",
                            "<em>cgene</em>",
                            "Molecular Effects of Spaceflight in the Mouse Eye after <em>Space</em> Shuttle Mission STS-135",
                            "Johnson <em>Space</em> Center (JSC)"
                        ]
                    }
                },
]